version: 2

sources:
  - name: retool_jaffle
    database: se-demo-340315
    schema: retool_jaffle
    tables:
      - name: stg_customers
        freshness:
            warn_after: {count: 2, period: hour}
            error_after: {count: 4, period: hour}
        loaded_at_field: _etl_loaded_at
      - name: stg_orders
        freshness:
            warn_after: {count: 2, period: hour}
            error_after: {count: 4, period: hour}
        loaded_at_field: _etl_loaded_at
      - name: stg_payments
        freshness:
            warn_after: {count: 2, period: hour}
            error_after: {count: 4, period: hour}
        loaded_at_field: _etl_loaded_at
